export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SOCIAL_AUTH_START = "SOCIAL_AUTH_START";
export const SOCIAL_AUTH_SUCCESS = "SOCIAL_AUTH_SUCCESS";
export const SOCIAL_AUTH_FAIL = "SOCIAL_AUTH_FAIL";

export const GET_SELECTED_USER_START = "GET_SELECTED_USER_START";
export const GET_SELECTED_USER_SUCCESS = "GET_SELECTED_USER_SUCCESS";
export const GET_SELECTED_USER_FAIL = "GET_SELECTED_USER_FAIL";

export const UPDATE_SELECTED_USER_START = "UPDATE_SELECTED_USER_START";
export const UPDATE_SELECTED_USER_SUCCESS = "UPDATE_SELECTED_USER_SUCCESS";
export const UPDATE_SELECTED_USER_FAIL = "UPDATE_SELECTED_USER_FAIL";

export const UPDATE_USER_IMAGE_START = "UPDATE_USER_IMAGE_START";
export const UPDATE_USER_IMAGE_SUCCESS = "UPDATE_USER_IMAGE_SUCCESS";
export const UPDATE_USER_IMAGE_FAIL = "UPDATE_USER_IMAGE_FAIL";

export const RESET_ERROR = "RESET_ERROR";
